networks:
  darts4dorks-network:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - darts4dorks-network
    volumes:
      - darts4dorks-data:/var/lib/mysql

  darts4dorks:
    image: darts4dorks:latest
    container_name: darts4dorks
    restart: unless-stopped
    ports:
      - 127.0.0.1:5000:5000
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - darts4dorks-network

volumes:
  darts4dorks-data:
