networks:
  network:
    driver: bridge

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - network
    volumes:
      - data:/var/lib/mysql

  darts4dorks:
    image: darts4dorks:latest 
    pull_policy: build
    container_name: darts4dorks
    restart: unless-stopped
    ports:
      - 127.0.0.1:8000:5000
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - network

volumes:
  data:
