"""Session cascading delete

Revision ID: 400efecbbaef
Revises: 06ffdb6ba45d
Create Date: 2025-05-06 20:10:53.969937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '400efecbbaef'
down_revision = '06ffdb6ba45d'
branch_labels = None
depends_on = None

# SQLite doesn't have named constraints so must be handled differently
bind = op.get_bind()
dialect = bind.dialect.name


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        if dialect != 'sqlite':
            batch_op.drop_constraint('attempt_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key('fk_attempt_session_id_session', 'session', ['session_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('session') as batch_op:
        if dialect != 'sqlite':
            batch_op.drop_constraint('session_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key('fk_session_user_id_user', 'user', ['user_id'], ['id'])


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        if dialect != 'sqlite':
            batch_op.drop_constraint('fk_attempt_session_id_session', type_='foreignkey')
        batch_op.create_foreign_key('attempt_ibfk_1', 'session', ['session_id'], ['id'])

    with op.batch_alter_table('session', schema=None) as batch_op:
        if dialect != 'sqlite':
            batch_op.drop_constraint('fk_session_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key('session_ibfk_1', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
