"""add unique constraint on target per session in attempt

Revision ID: db97e212be86
Revises: bbbbce6d77ac
Create Date: 2024-12-06 14:16:26.918315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db97e212be86'
down_revision = 'bbbbce6d77ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_target_per_session', ['target', 'session_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attempt', schema=None) as batch_op:
        batch_op.drop_constraint('unique_target_per_session', type_='unique')

    # ### end Alembic commands ###
